
session:
  key: u7pUYa_wj8ITfBmuo1Fwu_omiQHMsl8URQ6U750gjWE=
admin:
  email: admin@admin.com
  password: admin
database:
  host: 193.29.56.83
  port: 5432
  user: exchange_user
  password: exchange_user_password
  database: exchange
bot:

  token: 166356d6d5e459f
  group_id: 210525858


