
session:
  key: u7pUYa_wj8ITfBmuo1Fwu_omiQHMsl8URQ6U750gjWE=
admin:
  email: admin@admin.com
  password: admin
database:
  host: 
  port: 5432
  user: 
  password: 
  database: 
bot: 
  token: 
  group_id: 210525858


