"""next migration

Revision ID: 029e87f0231c
Revises: 
Create Date: 2022-02-25 17:37:55.076642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029e87f0231c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=False),
    sa.Column('diff', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('securites',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Unicode(), nullable=False),
    sa.Column('start_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('vk_id')
    )
    op.create_table('game_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_in_game', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyed_securites',
    sa.Column('user_in_game_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.String(length=10), nullable=False),
    sa.Column('ammount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_in_game_id'], ['game_users.id'], ondelete='CASCADE')
    )
    op.create_table('trade_jornal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sequrity_id', sa.String(length=10), nullable=False),
    sa.Column('operation', sa.String(length=30), nullable=False),
    sa.Column('ammount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['trade_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequrity_id'], ['securites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traded_securites',
    sa.Column('sequrity_id', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('market_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['market_event_id'], ['market_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['trade_rounds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequrity_id'], ['securites.id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traded_securites')
    op.drop_table('trade_jornal')
    op.drop_table('buyed_securites')
    op.drop_table('trade_rounds')
    op.drop_table('game_users')
    op.drop_table('users')
    op.drop_table('securites')
    op.drop_table('market_events')
    op.drop_table('games')
    # ### end Alembic commands ###
